config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  get 'search' => 'searches#search'
  get 'tag_search' => 'searches#tag_search'

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :rooms, only: [:create, :show]
  resources :messages, only: [:create]

  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    get 'search' => 'users#search'
  end

  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :introduction, presence: true

  has_many :group_users
  has_many :users, through: :group_users

  has_one_attached :image

  def get_group_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :correct_group, only: [:edit, :update]
  before_action :correct_group_mail, only: [:new_mail, :send_mail]

  def index
    @groups = Group.all
    @book = Book.new
  end

  def show
    @group = Group.find(params[:id])
    @book = Book.new
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users.push(current_user)
    # redirect_to  group_path(@group)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      @group.users.push(current_user)
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path(@group)
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    # redirect_to group_path(@group)
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    ContactMailer.send_mail(@mail_title, @mail_content, group_users).deliver_now
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def correct_group
    group = Group.find(params[:id])
    unless current_user.id == group.owner_id
      redirect_to groups_path
    end
  end

  def correct_group_mail
    group = Group.find(params[:group_id])
    unless current_user.id == group.owner_id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group_users_count.html.slim
- group.users[1..-1].each do |user|
  = link_to user.name, user_path(user.id)
  br

app/views/groups/_show.html.slim
- if group.users.include?(current_user)
  = link_to "Leave this group", group_path(group), method: :delete, data: {disable_with: 'Leave this group'}, remote: true, class: "btn btn-danger"
- else
  = link_to "Join this group", group_join_path(group), method: :get, data: {disable_with: 'Join this group'}, remote: true, class: "btn btn-success"

app/views/groups/destroy.js.erb
$('#group_buttons').html("<%= j(render "show", group: @group) %>");
$('.group_users_count').html("<%= j(render "group_users_count", group: @group) %>");

app/views/groups/edit.html.slim
.container
  .row
    .col-sm-12.col-md-8.col-lg-5.px-5.px-sm-0.mx-auto
      h2
        | Editing Group
      - if @group.errors.any?
        #error_explanation
          h3
            - if @group.errors.count == 1
              = @group.errors.count
              |  error prohibited this obj from being saved: 
            - else
              = @group.errors.count
              |  errors prohibited this obj from being saved: 
          ul
            - @group.errors.full_messages.each do |message|
              li
                = message
      = form_with model: @group, method: :patch do |f|
        .form-group
          = f.label :グループ名
          = f.text_field :name, class: "form-control"
        .form-group
          = f.label :紹介文
          = f.text_area :introduction, class: "form-control"
        .input-group.form-group
          = f.label :グループ画像
          = f.file_field :image, accept: "image/*", class: "form-control-file"
        .form-group
          = f.submit "Create Group", class: "btn btn-info"

app/views/groups/index.html.slim
.container
  .row
    .col-md-3
      = render "users/info", book: @book, user: current_user
    .col-md-8.offset-md-1.mt-4.mt-md-0
      h2
        | Groups
      table.table.table-hover
        thead
          tr
            th
            th
              | グループ名
            th
              | 紹介文
            th
              | メンバー数
            th[colspan="2"]
        tbody
          - @groups.each do |group|
            tr
              td
                = image_tag group.get_group_image(80, 80)
              td
                = link_to group.name, group_path(group)
              td
                = group.introduction
              td
                = group.users.count
              - if group.owner_id == current_user.id
                td
                  = link_to "Edit", edit_group_path(group), class: "btn btn-success"
              td[colspan="2"]

app/views/groups/join.js.erb
$('#group_buttons').html("<%= j(render "show", group: @group) %>");
$('.group_users_count').html("<%= j(render "group_users_count", group: @group) %>");

app/views/groups/new.html.slim
.container
  .row
    .col-sm-12.col-md-8.col-lg-5.px-5.px-sm-0.mx-auto
      h2
        | Create Group
      - if @group.errors.any?
        #error_explanation
          h3
            - if @group.errors.count == 1
              = @group.errors.count
              |  error prohibited this obj from being saved: 
            - else
              = @group.errors.count
              |  errors prohibited this obj from being saved: 
          ul
            - @group.errors.full_messages.each do |message|
              li
                = message
      = form_with model: @group do |f|
        .form-group
          = f.label :グループ名
          = f.text_field :name, class: "form-control"
        .form-group
          = f.label :紹介文
          = f.text_area :introduction, class: "form-control"
        .input-group.form-group
          = f.label :グループ画像
          = f.file_field :image, accept: "image/*", class: "form-control-file"
        .form-group
          = f.submit "Create Group", class: "btn btn-info"

app/views/groups/new_mail.html.slim
.container
  .row
    .col-sm-12.col-md-8.col-lg-5.px-5.px-sm-0.mx-auto
      h2
        | Event Mail
      = form_with url: group_send_mail_path(@group), method: :get, local: true do |f|
        .form-group
          = f.label :title
          = f.text_field :mail_title, class: "form-control"
        .form-group
          = f.label :content
          = f.text_area :mail_content, class: "form-control"
        .form-group.text-right
          = f.submit "送信", class: "btn btn-info"

app/views/groups/send_mail.html.slim
.container
  .row
    .col-sm-12.col-md-8.col-lg-5.px-5.px-sm-0.mx-auto
      h2
        | 送信が完了しました
      div
        p
          | 内容は以下の通りです。
        section
          h4
            | [タイトル]
          p
            = @mail_title
        section
          h4
            | [本文]
          p
            = safe_join(@mail_content.split("\n"),tag.br)

app/views/groups/show.html.slim
.container
  .row
    .col-md-3
      = render "users/info", book: @book, user: current_user
    .col-md-8.offset-md-1.mt-4.mt-md-0
      h2
        | Group Detail
      table.table.table-hover
        thead
          tr
            th
            th
              | グループ名
            th
              | 紹介文
            th
              | オーナー
            th
              | メンバー
            th[colspan="5"]
        tbody
          tr
            td
              = image_tag @group.get_group_image(80, 80)
            td
              = @group.name
            td
              = @group.introduction
            td
              = link_to @group.users[0].name, user_path(@group.users[0].id)
            td.group_users_count
              - @group.users[1..-1].each do |user|
                = link_to user.name, user_path(user.id)
                br
            td[colspan="2"]
            - if @group.owner_id == current_user.id
              td
                = link_to "Edit", edit_group_path(@group), class: "btn btn-success"
            - else
              td
                span#group_buttons
                  = render "show", group: @group
            - if @group.owner_id == current_user.id
              td
                = link_to 'Notice an Event', group_new_mail_path(@group), class: "btn btn-info"