config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  get 'search' => 'searches#search'
  get 'tag_search' => 'searches#tag_search'

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :rooms, only: [:create, :show]
  resources :messages, only: [:create]

  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    get 'search' => 'users#search'
  end

  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  has_many :book_comments, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :group_users
  has_many :groups, through: :group_users

  has_many :entries, dependent: :destroy
  # has_many :rooms, through: :entries
  has_many :messages, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user)
    unless self == user
      relationships.create(followed_id: user)
    end
  end

  def unfollow(user)
    relationships.find_by(followed_id: user).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(word, search)
    case search
    when "perfect"
      User.where("name LIKE ?", "#{word}").includes(profile_image_attachment: :blob)
    when "forward"
      User.where("name LIKE ?", "#{word}%").includes(profile_image_attachment: :blob)
    when "backward"
      User.where("name LIKE ?", "%#{word}").includes(profile_image_attachment: :blob)
    when "partial"
      User.where("name LIKE?", "%#{word}%").includes(profile_image_attachment: :blob)
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def index
    @users = User.includes(profile_image_attachment: :blob)
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.includes(:tags)
    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)

    # @today_book = @books.created_today
    # @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week

    unless @user.id == current_user.id
      @current_user_entry.each do |cu|
        @user_entry.each do |u|
          if cu.room_id == u.room_id
            @is_room = true
            @room_id = cu.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      created_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ?', "#{created_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_correct_user
    unless current_user.id == params[:id].to_i
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user), notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_books.html.slim
h2
  | Books
table.table.table-hover
  thead
    tr
      th
      th
        | Title
      th
        | Opinion
      th[colspan="6"]
  tbody[data-turbolinks="false"]
    - books.each do |book|
      tr
        td
          = link_to user_path(book.user.id) do
            = image_tag book.user.get_profile_image(80, 80)
        td
          = link_to book.title, book_path(book.id)
        td
          = book.body
        td
          - book.tags.each do |tag|
            = link_to tag.tag_name + ("\t"), tag_search_path(tag_id: tag.id)
          |  <td id="favorite_buttons_
          = book.id
          | ">
          = render "favorites/favorite", book: book
        td
          | コメント数：
          = book.book_comments.count
        td
          = render "books/rate", book: book
h2.mt-5
  | 投稿数の前日比・先週比(月曜日始まり)
table.table.table-bordered
  thead.table-primary
    tr
      th
        | 今日の投稿
      th
        | 昨日の投稿
      th
        | 前日比
  tbody
    tr
      td
        = books.created_days(0).count
      td
        = books.created_days(1).count
      - unless books.created_days(1).count == 0
        td
          - days_difference = books.created_days(0).count / books.created_days(1).count.to_f
          = (days_difference * 100).round
          | %
      - else
        td
          | 前日の投稿はありません
table.table.table-bordered
  thead.table-primary
    tr
      th
        | 今週の投稿
      th
        | 先週の投稿
      th
        | 先週比
  tbody
    tr
      td
        = this_week_book.count
      td
        = last_week_book.count
      - unless last_week_book.count == 0
        td
          - week_difference = this_week_book.count / last_week_book.count.to_f
          = (week_difference * 100).round
          | %
      - else
        td
          | 先週の投稿はありません
h2
  | 過去7日分の投稿数
table.table.table-bordered
  thead.table-primary
    tr
      th
        | 6日前
      th
        | 5日前
      th
        | 4日前
      th
        | 3日前
      th
        | 2日前
      th
        | 1日前
      th
        | 今日
  tbody
    tr
      - (0..6).reverse_each do |n|
        th
          = books.created_days(n).count
div
  canvas#myChart
.mt-5
  h6
    | 投稿数検索
  = form_with url: user_search_path(user), local: false, method: :get do |f|
    = f.date_field :created_at
    = f.submit "検索", class: "btn btn-primary"
  #search_result
    = render "users/search", search_book: search_book

javascript:
  $(document).on('turbolinks:load', function(){
    var ctx = document.getElementById('myChart');

    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [{
                label: '投稿した本の数',
                data: #{ books.past_week_count },
                backgroundColor: [
                    'rgba(0, 0, 0, 0)',
                ],
                borderColor: [
                    'rgba(0, 0, 255, 1)'
                ],
                borderWidth: 1,
                tension: 0.4
            }]
        },
        options: {
          plugins: {
            title: {
              display: true,
              text: '7日間の投稿数の比較',
            }
          },
          scales: {
            y: {
              beginAtZero: true,
              suggestedMax: 10,
              }
            }
        }
    });
  });

app/views/users/_follow_index.html.erb
<% users.each do |user| %>
  <tr>
    <td><%= image_tag user.get_profile_image(80, 80) %></td>
    <td><%= user.name %></td>
    <td>フォロー数：<%= user.followings.count %></td>
    <td>フォロワー数：<%= user.followers.count %></td>
    <td>
      <% unless current_user == user  %>
        <% if current_user.following?(user) %>
          <span class="btn_content">
            <%= link_to "フォロー外す", user_relationships_path(user), remote: true, method: :delete, class: "unfollow_btn" %>
          </span>
        <% else %>
          <span class="btn_content">
            <%= link_to "フォローする", user_relationships_path(user), remote: true, method: :post, class: "follow_btn" %>
          </span>
        <% end %>
      <% end %>
    </td>
    <td><%= link_to "Show", user_path(user.id) %></td>
  </tr>
<% end %>

app/views/users/_info.html.slim
h2
  | User info
= image_tag user.get_profile_image(100, 100), class: "mb-3"
table.table[data-turbolinks="false"]
  tbody
    tr
      th
        | name
      th
        = user.name
    tr
      th
        | introduction
      th
        = user.introduction
    tr
      th
        | follows
      th
        = link_to user.followings.count, user_follows_path(user.id)
    tr
      th
        | followers
      th
        = link_to user.followers.count, user_followers_path(user.id)
- if user.name != "guestuser"
  .row[data-turbolinks="false"]
    - if user == current_user
      = link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do
        i.fas.fa-user-cog
    - else
      - unless current_user == user
        - if current_user.following?(user)
          = link_to "フォロー外す", user_relationships_path(user), method: :delete, class: "btn btn-info btn-block"
          div
            - if current_user.following?(user) && user.following?(current_user)
              - if is_room
                = link_to "チャットをはじめる", room_path(room_id), class: "btn btn-outline-primary"
              - else
                = form_with model: room, url: rooms_path, local: true do |f|
                  .from-group
                    = fields_for entry do |e|
                      = e.hidden_field :user_id, value: user.id
                  .form-group
                    = f.submit "チャットをはじめる", class: "btn btn-outline-primary"
        - else
          = link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success btn-block"
h2.mt-3
  | New book
= form_with model: book, url: books_path do |f|
  .form-group
    = f.label :title
    = f.text_field :title, autofocus: true, class: "form-control"
  .form-group
    = f.label :opinion
    = f.text_area :body, rows: "5", class: "form-control"
  .form-group
    = f.label :tag
    = f.text_area :tag_name, placeholder: "複数入力する場合は , で区切ってください", class: "form-control"
  #book_rate.form-group
    = f.label :rate
    div
      = f.hidden_field :rate, id: :review_star
  .form-group
    = f.submit "Create Book", class: "btn btn-success"
= render "books/rate_info"

app/views/users/_search.html.slim
h4
  | 検索結果
table.table.table-bordered
  thead
    tr
      th
        | 投稿数
  tbody
    tr
      td
        - unless search_book.present?
          span
            | 日付を選択してください
        - else
          = search_book

app/views/users/edit.html.slim
.container
  .row
    .col-sm-12.col-md-8.col-lg-5.px-5.px-sm-0.mx-auto
      h2
        | User info
      - if @user.errors.any?
        #error_explanation
          h3
            - if @user.errors.count == 1
              = @user.errors.count
              |  error prohibited this obj from being saved: 
            - else
              = @user.errors.count
              |  errors prohibited this obj from being saved: 
          ul
            - @user.errors.full_messages.each do |message|
              li
                = message
      = form_with model: @user, url: user_path, method: :patch do |f|
        .form-group
          = f.label :name
          = f.text_field :name, autofocus: true, class: "form-control"
        .input-group
          = f.label :image
          = f.file_field :profile_image, accept: "image/*", class: "form-control-file"
        .form-group
          = f.label :introduction
          = f.text_area :introduction, class: "form-control"
        .form-group
          = f.submit "Update User", class: "btn btn-secondary"

app/views/users/index.html.slim
.container
  .row
    - if user_signed_in?
      .mx-auto.my-3
        = render "searches/search"
.container
  .row
    .col-md-3
      = render "info", book: @book, user: @user
    .col-md-8.offset-md-1.mt-4.mt-md-0
      h2
        | Users
      div
        = link_to "グループを作成する", new_group_path
        |  |
        = link_to "グループ一覧", groups_path
      table.table.table-hover
        thead
          tr
            th
              | image
            th
              | name
            th[colspan="4"]
        tbody
          - @users.each do |user|
            tr
              td
                = image_tag user.get_profile_image(80, 80)
              td
                = user.name
              td
                | フォロー数：
                = user.followings.count
              td
                | フォロワー数：
                = user.followers.count
              td
                - unless current_user == user
                  - if current_user.following?(user)
                    = link_to "フォロー外す", user_relationships_path(user), method: :delete
                  - else
                    = link_to "フォローする", user_relationships_path(user), method: :post
              td
                = link_to "Show", user_path(user.id)

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'users/search', search_book: @search_book) %>");

app/views/users/show.html.slim
.container
  .row
    - if user_signed_in?
      .mx-auto.my-3
        = render "searches/search"
.container
  .row
    .col-md-3
      = render "info", book: @book, user: @user, is_room: @is_room, room_id: @room_id, room: @room, entry: @entry
    .col-md-8.offset-md-1.mt-4.mt-md-0
      = render "books", books: @books, user: @user, tags: @tags, this_week_book: @this_week_book, last_week_book: @last_week_book, search_book: @search_book