config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  get 'search' => 'searches#search'
  get 'tag_search' => 'searches#tag_search'

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :rooms, only: [:create, :show]
  resources :messages, only: [:create]

  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    get 'search' => 'users#search'
  end

  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1,
  }, presence: true

  is_impressionable counter_cache: true

  belongs_to :user

  has_many :favorites, dependent: :destroy
  # has_many :favorited_users, through: :favorites, source: :book   忘備録用にコメントアウト

  has_many :book_comments, dependent: :destroy

  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(word, search)
    case search
    when "perfect"
      Book.where("title LIKE ?", "#{word}").includes(:user ,user: {profile_image_attachment: :blob})
    when "forward"
      Book.where("title LIKE ?", "#{word}%").includes(:user ,user: {profile_image_attachment: :blob})
    when "backward"
      Book.where("title LIKE ?", "%#{word}").includes(:user ,user: {profile_image_attachment: :blob})
    when "partial"
      Book.where("title LIKE?", "%#{word}%").includes(:user ,user: {profile_image_attachment: :blob})
    end
  end

  def save_tag(tag_list)
    unless tags.nil?
      book_tags_records = BookTag.where(book_id: id)
      book_tags_records.destroy_all
    end

    tag_list.each do |tag|
      inspected_tag = Tag.where(tag_name: tag).first_or_create
      tags << inspected_tag
    end
  end

  # scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  # scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: Time.current.beginning_of_week..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: (Time.current - 1.week).beginning_of_week..(Time.current - 1.week).end_of_week) }

  scope :created_days, -> (n) { where(created_at: n.days.ago.all_day) }

  def self.past_week_count
    (0..6).map { |n| created_days(n).count }.reverse
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_book, only: [:edit, :update, :destroy]

  helper_method :sort_column, :sort_direction

  def index
    @book = Book.new
    @books = Book.includes(:user ,user: {profile_image_attachment: :blob}).order("#{sort_column} #{sort_direction}")
    @user = current_user
    @tags = Tag.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag_list = params[:book][:tag_name].split(",")
    if @book.save
      @book.save_tag(tag_list)
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.new
    book = Book.find(params[:id])
    @user = book.user
    impressionist(book, nil, unique: [:ip_address])
    @book_comment_new = BookComment.new
    @book_show = book
    @tags = book.tags
    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_entry.each do |cu|
        @user_entry.each do |u|
          if cu.room_id == u.room_id
            @is_room = true
            @room_id = cu.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @book = Book.find(params[:id])
    tags = @book.tags.all
    @tag_names = tags.pluck(:tag_name).join(",") + ","
  end

  def update
    @book = Book.find(params[:id])
    tag_list = params[:book][:tag_name].split(",")
    if @book.update(book_params)
      @book.save_tag(tag_list)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end

  def correct_book
    book = Book.find(params[:id])
    if current_user.id != book.user_id
      redirect_to books_path
    end
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    Book.column_names.include?(params[:sort]) ? params[:sort] : 'id'
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def sort_order(column, name)
    direction = (column == sort_column && sort_direction == 'asc') ? 'desc' : 'desc'
    link_to name, { sort: column, direction: direction }, remote: true
  end
end

app/views/books/_books.html.slim
h2
  | Books
#sort
  = sort_order "created_at", "新しい順"
  |   |
  = sort_order "rate", "評価の高い順"
table.table.table-hover
  thead
    tr
      th
      th
        | Title
      th
        | Opinion
      th
        | Tag
      th[colspan="7"]
  tbody#book_index
    = render "index", {books: books, tags: tags}

app/views/books/_index.html.slim
- books.each do |book|
  tr
    td
      = link_to user_path(book.user.id) do
        = image_tag book.user.get_profile_image(80, 80)
    td
      = link_to book.title, book_path(book.id)
    td
      = book.body
    td
      - book.tags.find_each do |tag|
        = link_to tag.tag_name, tag_search_path(tag_id: tag.id)
        - break
    td[colspan="3"]
    |  <td id="favorite_buttons_
    = book.id
    | ">
    = render "favorites/favorite", book: book
    td
      | コメント数：
      = book.book_comments.count
    td
      = render "books/rate", book: book
    td
      | 閲覧数：
      = book.impressionist_count

app/views/books/_info.html.slim
h2
  | User info
= image_tag user.get_profile_image(100, 100), class: "mb-3"
table.table
  tbody
    tr
      th
        | name
      th
        = user.name
    tr
      th
        | introduction
      th
        = user.introduction
    tr
      th
        | follows
      th
        = link_to user.followings.count, user_follows_path(user.id)
    tr
      th
        | followers
      th
        = link_to user.followers.count, user_followers_path(user.id)
.row
  - if user == current_user
    = link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do
      i.fas.fa-user-cog
  - else
    - unless current_user == user
      - if current_user.following?(user)
        = link_to "フォロー外す", user_relationships_path(user), method: :delete, class: "btn btn-info btn-block"
        div
          - if current_user.following?(user) && user.following?(current_user)
            - if is_room
              = link_to "チャットをはじめる", room_path(room_id)
            - else
              = form_with model: room, url: rooms_path, local: true do |f|
                = fields_for entry do |e|
                  = e.hidden_field :user_id, value: user.id
                = f.submit "チャットをはじめる"
      - else
        = link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success btn-block"
h2.mt-3
  | New book
= form_with model: book, url: books_path do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :opinion
    = f.text_area :body, rows: "5", class: "form-control"
  .form-group
    = f.label :tag
    = f.text_area :tag_name, placeholder: "複数入力する場合は , で区切ってください", class: "form-control"
  #book_rate.form-group
    = f.label :rate
    div
      = f.hidden_field :rate, id: :review_star, class: "d-block"
  .form-group
    = f.submit "Create Book", class: "btn btn-success"
= render "books/rate_info"

app/views/books/_rate.html.erb
<span id="book_rate_<%= book.id %>"><% book.id %></span>
  <script>
    $('#book_rate_<%= book.id %>').empty();
    $('#book_rate_<%= book.id %>').raty({
      size: 8,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      readOnly: true,
      score: <%= book.rate %>,
    });
  </script>

app/views/books/_rate_edit.html.erb
<script>
  $('#book_rate').empty();
  $('#book_rate').raty({
    size: 36,
    starOff: "<%= asset_path('star-off.png') %>",
    starOn: "<%= asset_path('star-on.png') %>",
    scoreName: 'book[rate]',
    readOnly: true,
    score: <%= book.rate %>
  });
</script>

app/views/books/_rate_info.html.erb
<script>
  $('#book_rate').empty();
  $('#book_rate').raty({
    size: 36,
    starOff: "<%= asset_path('star-off.png') %>",
    starOn: "<%= asset_path('star-on.png') %>",
    scoreName: 'book[rate]',
    half: false,
  });
</script>

app/views/books/edit.html.slim
.container
  .row
    .col-sm-12.col-md-8.col-lg-5.px-5.px-sm-0.mx-auto
      h1
        | Editing Book
      - if @book.errors.any?
        #error_explanation
          h3
            - if @book.errors.count == 1
              = @book.errors.count
              |  error prohibited this obj from being saved:
            - else
              = @book.errors.count
              |  errors prohibited this obj from being saved:
          ul
            - @book.errors.full_messages.each do |message|
              li
                = message
      = form_with model: @book, url: book_path, method: :patch do |f|
        .form-group
          = f.label :title
          = f.text_field :title, autofocus: true, class: "form-control"
        .form-group
          = f.label :opinion
          = f.text_area :body, class: "form-control"
        .form-group
          = f.label :tag
          = f.text_area :tag_name, value: @tag_names, placeholder: "複数入力する場合は , で区切ってください", class: "form-control"
             = @tag_names
        #book_rate.form-group
          = f.label :rate
          div
            = f.hidden_field :rate, id: :review_star
        .form-group
          = f.submit "Update Book", class: "btn btn-success"
      = link_to "Show", book_path(@book.id)
      |  |
      = link_to "Back", books_path
= render "rate_edit", book: @book

app/views/books/index.html.slim
.container
  .row
    - if user_signed_in?
      .mx-auto.my-3
        = render "searches/search"
- if @book.errors.any?
  #error_explanation
    h3
      - if @book.errors.count == 1
        = @book.errors.count
        |  error prohibited this obj from being saved: 
      - else
        = @book.errors.count
        |  errors prohibited this obj from being saved: 
    ul
      - @book.errors.full_messages.each do |message|
        li
          = message
.container
  .row
    .col-md-3
      = render "users/info", book: @book, user: @user
    .col-md-8.offset-md-1.mt-4.mt-md-0
      = render "books", {books: @books, tags: @tags}

app/views/books/index.js.erb
$("#book_index").html("<%= j(render 'index', {user: @user, book: @book, books: @books, tags: @tags}) %>");

app/views/books/show.html.slim
.container
  .row
    - if user_signed_in?
      .mx-auto.my-3
        = render "searches/search"
.container
  .row
    .col-md-3
      = render "info", book: @book, user: @user, is_room: @is_room, room_id: @room_id, room: @room, entry: @entry
    .col-md-8.offset-md-1.mt-4.mt-md-0
      h2
        | Book detail
      table.table.table-hover
        tbody
          tr
            td
              = link_to user_path(@user.id) do
                = image_tag @user.get_profile_image(100, 100)
                br
                = @user.name
            - book = @user.books.find(params[:id])
            td
              = link_to book.title, book_path(book)
            td
              = book.body
            td
              - @tags.each do |tag|
                div
                  = link_to tag.tag_name, tag_search_path(tag_id: tag.id)
            |  <td id="favorite_buttons_
            = book.id
            | ">
            = render "favorites/favorite", book: book
            td#comment_count
              = render "book_comments/comment_count", book: book
            td
              = render "rate", book: @book_show
            td
              |  閲覧数：
              = book.impressionist_count
            - if @user == current_user
              td
                = link_to "Edit", edit_book_path(book), class: "btn btn-sm btn-success"
              td
                = link_to "Destroy", book_path, method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-sm btn-danger"
      table.table.table-hover

      h4.mt-5
        | Comments
      table
        tbody#comment
          = render "book_comments/book_comment", book: book
      .row
        .col-12.mt-3
          = form_with model: [@book_show, @book_comment_new], method: :post, local: false do |f|
            .form-group
              = f.text_area :comment, autofocus: true, rows: "5", class: "form-control text_area"
            = f.hidden_field :book_id, value: @book_show.id
            .form-group
              = f.submit "Comment Submit", class: "btn btn-sm btn-success"