config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  get 'search' => 'searches#search'
  get 'tag_search' => 'searches#tag_search'

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :rooms, only: [:create, :show]
  resources :messages, only: [:create]

  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    get 'search' => 'users#search'
  end

  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params[:model]
    if @model == 'user'
      @users = User.looks(params[:word], params[:search])
    else
      @books = Book.looks(params[:word], params[:search])
    end
  end

  def tag_search
    @tags = Tag.includes([:tags])
    if params[:tag_word]
      if params[:tag_word] == ""
        @books = Book.includes(:user, :tags, :book_tags ,user: {profile_image_attachment: :blob})
        @tag_name = "All books"
      else
        @tag = Tag.find_by(tag_name: params[:tag_word])
        @books = @tag.books
        @tag_name = @tag.tag_name
      end
    else
      @tag = Tag.find(params[:tag_id])
      @books = @tag.books
      @tag_name = @tag.tag_name
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.slim
.form-inline
  div
    = form_with url: search_path, method: :get, class: "form-group" do |f|
      = f.search_field :word, placeholder: "ユーザーまたは本を検索" , class: "form-control"
      = f.select :model, options_for_select({ "User" => "user", "Book" => "book" }), {}, class: "form-control form-control-sm ml-1"
      = f.select :search, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }), {}, class: "form-control form-control-sm ml-1"
      = f.submit "検索", class: "btn btn-primary ml-1"
  .ml-3
    = form_with url: tag_search_path, method: :get, class: "form-group" do |f|
      = f.search_field :tag_word, placeholder: "タグを検索", class: "form-control"
      = f.submit "検索", class: "btn btn-primary ml-1"

app/views/searches/search.html.slim
.container
  .row
    - if user_signed_in?
      .mx-auto.my-3
        = render "searches/search"
.mx-auto.col-12.col-lg-10.mt-3.px-3
  h2
    | Results index
  table.table.table-hover.table-inverse
    - if @model == "user"
      thead
        tr
          th
            | Image
          th
            | name
          th[colspan="3"]
      tbody
        - @users.each do |user|
          tr
            td
              = image_tag user.get_profile_image(60, 60)
            td
              = user.name
            td
              = link_to "Show", user_path(user)
    - else
      thead
        tr
          th
          th
            | Title
          th
            | Opinion
          th[colspan="2"]
      tbody
        - @books.each do |book|
          tr
            td
              = link_to user_path(book.user) do
                = image_tag book.user.get_profile_image(60, 60,)
                br
                = book.user.name
            td
              = link_to book.title, book_path(book)
            td
              = book.body
            td[colspan="3"]

app/views/searches/tag_search.html.slim
.container
  .row
    - if user_signed_in?
      .mx-auto.my-3
        = render "searches/search"
.mx-auto.col-12.col-lg-10.mt-3.px-3
  h2
    | Books search for "
    = @tag_name
    | "
  table.table.table-hover
    thead
      tr
        th
        th
          | Title
        th
          | Opinion
        th
          | Tag
        th[colspan="3"]
    tbody
      - @books.each do |book|
        tr
          td
            = link_to user_path(book.user) do
              = image_tag book.user.get_profile_image(60, 60,)
              br
              = book.user.name
          td
            = link_to book.title, book_path(book)
          td
            = book.body
          td
            - book.tags.each do |name|
              = link_to name.tag_name + "\t", tag_search_path(tag_id: name.id)
          |  <td id="favorite_buttons_
          = book.id
          | ">
          = render "favorites/favorite", book: book
          td
            | コメント数：
            = book.book_comments.count
          td
            = render "books/rate", book: book